cockroachdb:
  conf:
    useHostLocality:
      enabled: true

  statefulset:
    serviceAccount:
      create: true
      name: cockroachdb
  service:
    public:
      type: LoadBalancer
      annotations:
        cloud.google.com/load-balancer-type: Internal
  init:
    jobAnnotations:
      argocd.argoproj.io/hook: Sync
